---

- hosts: dcnm_controllers
  gather_facts: false

  vars:
    fabric: PRODUCTION_FABRIC

  tasks:

    - name: Change interface mode
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric }}"
        state: replaced                      
        config:
          - name: eth1/6                       
            type: eth
            switch:
              - "172.16.16.112"
              - "172.16.16.113"
            deploy: true                  
            profile:
              admin_state: true      
              mode: access               

    - name: Create overlay network
      cisco.dcnm.dcnm_network:
        fabric: "{{ fabric }}"
        state: merged
        config:
        - net_name: Ansible_Network
          vrf_name: Ansible_VRF
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          gw_ip_subnet: '172.30.100.1/24'
          attach:
          - ip_address: 172.16.16.112
            ports: [Ethernet1/6]
            int_desc: "Ansible attached interface"
            deploy: true
          - ip_address: 172.16.16.113
            ports: [Ethernet1/6]
            int_desc: "Ansible attached interface"
            deploy: true