---

- hosts: dcnm_controllers
  gather_facts: false

  vars:
    fabric: Ansible_Fabric

  tasks:

    - name: Replace port channel interfaces
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric }}"
        state: replaced                       # only choose from [merged, replaced, deleted, overridden, query]
        config:
          - name: eth1/4                       # should be of the form po<port-id>
            type: eth                          # choose from this list [pc, vpc, sub_int, lo, eth]
            switch:
              - "172.16.16.112"
              - "172.16.16.113"                 # provide the switch information where the config is to be deployed
            deploy: true                      # choose from [true, false]
            profile:
              admin_state: true              ## choose from [true, false]
              mode: access                     # choose from [trunk, access, l3, monitor]
              
    - name: Create overlay network
      cisco.dcnm.dcnm_network:
        fabric: "{{ fabric }}"
        state: merged
        config:
        - net_name: Ansible_Network
          vrf_name: Ansible_VRF
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          gw_ip_subnet: '172.30.100.1/24'
          attach:
          - ip_address: 172.16.16.112
            ports: [Ethernet1/6]
            int_desc: "Ansible attached interface"
            deploy: true
          - ip_address: 172.16.16.113
            ports: [Ethernet1/6]
            int_desc: "Ansible attached interface"
            deploy: true