---

- hosts: dcnm_controllers
  gather_facts: false

  vars:
    fabric: PRODUCTION_FABRIC_NEW

  tasks:
    - name: Query all VRFs deployed within the fabric
      cisco.dcnm.dcnm_vrf:
        fabric: "{{ fabric }}"
        state: query
      register: query_vrf
    - debug: var=query_vrf